#!/usr/bin/env sh
set -e
npm run format
git add -A
npm run lint
npm run typecheck
npm run build
npm test
MC_ENABLE=1 MC_TIMEOUT_MS=3000 MC_MAX_PATHS=100 MC_BRANCH_LIMIT=4 MC_NODES=3 MC_CANDIDATES=2 MC_ENTRIES=2 node --test --test-reporter=spec tests/correctness/model_checker.spec.js
